### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by Luidog** [geistinteractive/fm-webviewer-bridge#5]
Would you consider a pull request implementing a standard code format?

In past  projects we have leveraged [prettier](https://prettier.io) and [eslint](https://eslint.org). I propose using the same linters and code formatting as we used in [Modular FileMaker](https://github.com/modularfilemaker) projects.

**Comment by toddgeist** [comment]
prettier should already be in place.  But i am ok with eslint
